name: r2d
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - psutil==5.7.2
#  - pytorch==1.6.0
  - pip==21.3.1
  - python==3.9
#  - pip:
#      - tensorboard==2.3.0
#      - tensorboardx==2.1
